In [2]:
import numpy as np

In [10]:
N = 4
B = 10
s = 2*np.random.randint(0,2, (B,N))-1
Ju = np.arange(N*(N-1)/2)
row, col = np.triu_indices(N,k=1)
J = np.zeros((N,N))
J [row,col] = Ju
J += J.T

In [17]:
s

array([[-1,  1,  1,  1],
       [ 1,  1, -1, -1],
       [ 1, -1, -1,  1],
       [-1,  1, -1,  1],
       [ 1,  1, -1,  1],
       [-1, -1,  1,  1],
       [ 1,  1, -1,  1],
       [-1, -1,  1,  1],
       [-1, -1, -1,  1],
       [-1, -1,  1,  1]])

In [29]:
(s@J)*s

array([[ -3.,   7.,   7.,   7.],
       [ -3.,  -7.,   1.,  -1.],
       [  1.,  -1.,  -3.,  -7.],
       [ -1.,   1.,  -7.,  -3.],
       [  1.,   1.,  -9.,   1.],
       [ -3.,  -7.,   1.,  -1.],
       [  1.,   1.,  -9.,   1.],
       [ -3.,  -7.,   1.,  -1.],
       [ -1.,  -1.,  -1., -11.],
       [ -3.,  -7.,   1.,  -1.]])

In [26]:
np.dot(J[0], s[5])

3.0

In [18]:
J[0]

array([0., 0., 1., 2.])