In [2]:
import numpy as np

In [42]:
N = 4
B = 10
s = 2*np.random.randint(0,2, (B,N))-1
Ju = np.arange(N*(N-1)/2)
row, col = np.triu_indices(N,k=1)
J = np.zeros((N,N))
J [row,col] = Ju
J += J.T

In [43]:
s

array([[-1,  1, -1,  1],
       [-1,  1, -1, -1],
       [-1,  1, -1, -1],
       [ 1, -1,  1,  1],
       [-1, -1,  1, -1],
       [-1,  1,  1, -1],
       [ 1,  1,  1,  1],
       [ 1, -1, -1,  1],
       [ 1, -1,  1, -1],
       [ 1,  1,  1,  1]])

In [44]:
s.shape

(10, 4)

In [45]:
J

array([[0., 0., 1., 2.],
       [0., 0., 3., 4.],
       [1., 3., 0., 5.],
       [2., 4., 5., 0.]])

In [84]:
t = np.dot(s,J)
t.shape

(10, 4)

In [85]:
np.matmul(s,J)

array([[ 1.,  1.,  7., -3.],
       [-3., -7., -3., -3.],
       [-3., -7., -3., -3.],
       [ 3.,  7.,  3.,  3.],
       [-1., -1., -9., -1.],
       [-1., -1., -3.,  7.],
       [ 3.,  7.,  9., 11.],
       [ 1.,  1.,  3., -7.],
       [-1., -1., -7.,  3.],
       [ 3.,  7.,  9., 11.]])

In [89]:
s[..., None]*J[:,None,:]

ValueError: operands could not be broadcast together with shapes (10,4,1) (4,1,4) 

In [124]:
A = np.array([[0, 1],  
            [2, 3],  
            [4, 5]])   

B = np.array([[ 6,  7],  
           [ 8,  9]])

In [144]:
p=A[:,:,None]*A[:,None,:]*B
p

array([[[  0,   0],
        [  0,   9]],

       [[ 24,  42],
        [ 48,  81]],

       [[ 96, 140],
        [160, 225]]])